name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'PhysicksKim/FootballStreamOverlay'
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Checkout Pages Repository
        uses: actions/checkout@v2
        with:
          repository: 'PhysicksKim/FootballScoreBoard-gyechunhoe'
          token: ${{ secrets.SCOREBOARD_GYECHUNHOE_ACTION }}
          path: 'pages_repo'

      - name: Copy Files
        run: |
          rm -rf pages_repo/docs/*.*
          rm -rf pages_repo/docs/assets
          cp -r dist/* pages_repo/docs/

      - name: Commit and Push
        run: |
          cd pages_repo
          git config user.name PhysicksKim
          git config user.email PhysicksKim@gmail.com
          git add docs/
          git commit -m "Deploy GitHub Pages"
          git push
